title: "Tratado de Alta Hechicería, Alquimia y Transmutación Ígnea | Maestro Zoroastro"
author: "Maestro Zoroastro"
markdown: kramdown
highlighter: rouge
permalink: /:title/
exclude:
  - README.md
  - LICENSE
